#ifndef LIBSMARTCARD_READER_QT_GLOBAL_H
#define LIBSMARTCARD_READER_QT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIBSMARTCARD_READER_QT_LIB
# define LIBSMARTCARD_READER_QT_EXPORT Q_DECL_EXPORT
#else
# define LIBSMARTCARD_READER_QT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBSMARTCARD_READER_QT_GLOBAL_H
